apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: techtrends
    spec:
      containers:
        ## Set the image to be executed inside the container and image pull policy
      - image: adrianagorri/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: techtrends
        ## Expose the port the container is listening on.
        ports:
        - containerPort: {{ .Values.containerPort }}
        ## Define the rules for the liveness probes.
        livenessProbe:
           httpGet:
             path: {{ .Values.livenessProbe.httpGet.path }}
             port: {{ .Values.livenessProbe.httpGet.port }}
        ## Define the rules for the readiness probes.
        readinessProbe:
           httpGet:
             path: {{ .Values.readinessProbe.httpGet.path }}
             port: {{ .Values.readinessProbe.httpGet.port }}
        ## Set the resources requests and limits for an application.
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        #resources: {}
status: {}
